# Site settings
name: INODENT
title: INODENT | Inovație - Compasiune - Experiență  
description: Cabinet stomatologic specializat in tratamente cu implanturi dentare la prețuri accesibile. Ne gasiți pe Bdul Octavian Goga Nr 21, Sector 3, Bucuresti.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://inodent.ro" # the name of your domain
logo_url: /logo.png
oldname: ex IQDENT

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: INODENT
    hero_subtitle: ex IQDENT
    hero_description: Inovație - Compasiune - Experiență  

# Contact form
api_token: be4d9d546a4bc4f5fb27cd142eff4336

# Contact info
contact:
    phone: 0754 523 624
    email: inodent.ro@gmail.com
    address: Bdul Octavian Goga, Nr 21, Bl M103, Sc 2, Ap 37, Bucuresti
    directions: "Punct de reper: intersectia Nerva Traian cu Octavian Goga, langa hotelul Double Tree"
    fb_messages : https://www.facebook.com/messages/t/inodent.ro
    fb_reviews: https://www.facebook.com/dririnaalexandru/reviews
    
    irina:
        phone: 0766 748 971
        facebook : https://www.facebook.com/dririnaalexandru
        
    petronela:
        phone: 0721 502 570
        
offer:
    expiry: 31 Decembrie 2018

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: inchis

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Bdul Octavian Goga Nr 21, Sector 3, Bucuresti
    address_details: svg/min/logo.svg
    key: AIzaSyBjpBjFh9xbRqw8jBS6vV4d53vlWpjDTpI


# Social settings
facebook: https://www.facebook.com/inodent.ro
twitter: https://twitter.com/inodent_ro
instagram: https://www.instagram.com/inodent.ro
youtube: 
skype: 
feed: yes

# Footer
copyright: © 2015 INODENT - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-105983640-1
google_verification:


gems:
    - jekyll-sitemap
